<?php

/**
 * This is the model base class for the table "customer_c_group".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CustomerCGroup".
 *
 * Columns in table "customer_c_group" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $user_id
 * @property integer $c_group_id
 *
 */
abstract class BaseCustomerCGroup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'customer_c_group';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Customer Cgroup|Customer Cgroups', $n);
	}

	public static function representingColumn() {
		return array(
			'user_id',
			'c_group_id',
		);
	}

	public function rules() {
		return array(
			array('user_id, c_group_id', 'required'),
			array('user_id, c_group_id', 'numerical', 'integerOnly'=>true),
			array('user_id, c_group_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		$localeCode = Yii::app()->getLanguage(); 

		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'user_id' => Yii::t('label', 'User'),
			'c_group_id' => Yii::t('label', 'C Group'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('c_group_id', $this->c_group_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}