<?php

/**
 * This is the model base class for the table "geo_zone".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GeoZone".
 *
 * Columns in table "geo_zone" available as properties of the model,
 * followed by relations of table "geo_zone" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $date_modified
 * @property string $date_added
 *
 * @property ZoneGeoZone[] $zoneGeoZones
 */
abstract class BaseGeoZone extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'geo_zone';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Geo Zone|Geo Zones', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, description', 'required'),
			array('name', 'length', 'max'=>32),
			array('description', 'length', 'max'=>255),
			array('date_modified, date_added', 'safe'),
			array('date_modified, date_added', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, date_modified, date_added', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		$localeCode = Yii::app()->getLanguage(); 

		return array(
			'zoneGeoZones' => array(self::HAS_MANY, 'ZoneGeoZone', 'geo_zone_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('label', 'ID'),
			'name' => Yii::t('label', 'Name'),
			'description' => Yii::t('label', 'Description'),
			'date_modified' => Yii::t('label', 'Date Modified'),
			'date_added' => Yii::t('label', 'Date Added'),
			'zoneGeoZones' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('date_modified', $this->date_modified, true);
		$criteria->compare('date_added', $this->date_added, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}