<?php

/**
 * This is the model base class for the table "product_filter".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductFilter".
 *
 * Columns in table "product_filter" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $product_id
 * @property integer $filter_id
 *
 */
abstract class BaseProductFilter extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'product_filter';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Product Filter|Product Filters', $n);
	}

	public static function representingColumn() {
		return array(
			'product_id',
			'filter_id',
		);
	}

	public function rules() {
		return array(
			array('product_id, filter_id', 'required'),
			array('product_id, filter_id', 'numerical', 'integerOnly'=>true),
			array('product_id, filter_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		$localeCode = Yii::app()->getLanguage(); 

		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'product_id' => Yii::t('label', 'Product'),
			'filter_id' => Yii::t('label', 'Filter'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('filter_id', $this->filter_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}