<?php

/**
 * This is the model base class for the table "zone_geo_zone".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ZoneGeoZone".
 *
 * Columns in table "zone_geo_zone" available as properties of the model,
 * followed by relations of table "zone_geo_zone" available as properties of the model.
 *
 * @property integer $id
 * @property integer $country_id
 * @property integer $zone_id
 * @property integer $geo_zone_id
 * @property string $date_added
 * @property string $date_modified
 *
 * @property Country $country
 * @property Zone $zone
 * @property GeoZone $geoZone
 */
abstract class BaseZoneGeoZone extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'zone_geo_zone';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Zone Geo Zone|Zone Geo Zones', $n);
	}

	public static function representingColumn() {
		return 'date_added';
	}

	public function rules() {
		return array(
			array('country_id, geo_zone_id', 'required'),
			array('country_id, zone_id, geo_zone_id', 'numerical', 'integerOnly'=>true),
			array('date_added, date_modified', 'safe'),
			array('zone_id, date_added, date_modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, country_id, zone_id, geo_zone_id, date_added, date_modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		$localeCode = Yii::app()->getLanguage(); 

		return array(
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
			'zone' => array(self::BELONGS_TO, 'Zone', 'zone_id'),
			'geoZone' => array(self::BELONGS_TO, 'GeoZone', 'geo_zone_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('label', 'ID'),
			'country_id' => null,
			'zone_id' => null,
			'geo_zone_id' => null,
			'date_added' => Yii::t('label', 'Date Added'),
			'date_modified' => Yii::t('label', 'Date Modified'),
			'country' => null,
			'zone' => null,
			'geoZone' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('zone_id', $this->zone_id);
		$criteria->compare('geo_zone_id', $this->geo_zone_id);
		$criteria->compare('date_added', $this->date_added, true);
		$criteria->compare('date_modified', $this->date_modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}