<?php

/**
 * This is the model base class for the table "company_structure".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompanyStructure".
 *
 * Columns in table "company_structure" available as properties of the model,
 * followed by relations of table "company_structure" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $parent_id
 * @property integer $type_id
 * @property integer $location_id
 * @property string $create_at
 * @property string $lastedit_at
 *
 * @property CompanyStructureType $type
 * @property CompanyStructure $parent
 * @property CompanyStructure[] $companyStructures
 * @property Location $location
 */
abstract class BaseCompanyStructure extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'company_structure';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Company Structure|Company Structures', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, create_at', 'required'),
			array('parent_id, type_id, location_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>128),
			array('lastedit_at', 'safe'),
			array('parent_id, type_id, location_id, lastedit_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, parent_id, type_id, location_id, create_at, lastedit_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'type' => array(self::BELONGS_TO, 'CompanyStructureType', 'type_id'),
			'parent' => array(self::BELONGS_TO, 'CompanyStructure', 'parent_id'),
			'companyStructures' => array(self::HAS_MANY, 'CompanyStructure', 'parent_id'),
			'location' => array(self::BELONGS_TO, 'Location', 'location_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'parent_id' => null,
			'type_id' => null,
			'location_id' => null,
			'create_at' => Yii::t('app', 'Create At'),
			'lastedit_at' => Yii::t('app', 'Lastedit At'),
			'type' => null,
			'parent' => null,
			'companyStructures' => null,
			'location' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('location_id', $this->location_id);
		$criteria->compare('create_at', $this->create_at, true);
		$criteria->compare('lastedit_at', $this->lastedit_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}