<?php

/**
 * This is the model base class for the table "attribute_description".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AttributeDescription".
 *
 * Columns in table "attribute_description" available as properties of the model,
 * followed by relations of table "attribute_description" available as properties of the model.
 *
 * @property integer $attribute_id
 * @property string $locale_code
 * @property string $name
 *
 * @property Attribute $attribute
 */
abstract class BaseAttributeDescription extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'attribute_description';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Attribute Description|Attribute Descriptions', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('attribute_id, locale_code, name', 'required'),
			array('attribute_id', 'numerical', 'integerOnly'=>true),
			array('locale_code', 'length', 'max'=>5),
			array('name', 'length', 'max'=>64),
			array('attribute_id, locale_code, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		$localeCode = Yii::app()->getLanguage(); 

		return array(
			'attribute' => array(self::BELONGS_TO, 'Attribute', 'attribute_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'attribute_id' => null,
			'locale_code' => Yii::t('label', 'Locale Code'),
			'name' => Yii::t('label', 'Name'),
			'attribute' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('attribute_id', $this->attribute_id);
		$criteria->compare('locale_code', $this->locale_code, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}