<?php

/**
 * This is the model base class for the table "location_group".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LocationGroup".
 *
 * Columns in table "location_group" available as properties of the model,
 * followed by relations of table "location_group" available as properties of the model.
 *
 * @property integer $location_id
 * @property integer $group_id
 *
 * @property Group $group
 * @property Location $location
 */
abstract class BaseLocationGroup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'location_group';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LocationGroup|LocationGroups', $n);
	}

	public static function representingColumn() {
		return 'location_id';
	}

	public function rules() {
		return array(
			array('location_id, group_id', 'required'),
			array('location_id, group_id', 'numerical', 'integerOnly'=>true),
			array('location_id, group_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'group' => array(self::BELONGS_TO, 'Group', 'group_id'),
			'location' => array(self::BELONGS_TO, 'Location', 'location_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'location_id' => null,
			'group_id' => null,
			'group' => null,
			'location' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('location_id', $this->location_id);
		$criteria->compare('group_id', $this->group_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}